package com.ctbri.wwcc.greenrobot;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ctbri.wwcc.greenrobot.HotLine;

import com.ctbri.wwcc.greenrobot.HotLineDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig hotLineDaoConfig;

    private final HotLineDao hotLineDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        hotLineDaoConfig = daoConfigMap.get(HotLineDao.class).clone();
        hotLineDaoConfig.initIdentityScope(type);

        hotLineDao = new HotLineDao(hotLineDaoConfig, this);

        registerDao(HotLine.class, hotLineDao);
    }
    
    public void clear() {
        hotLineDaoConfig.getIdentityScope().clear();
    }

    public HotLineDao getHotLineDao() {
        return hotLineDao;
    }

}
