package com.ctbri.wwcc.greenrobot;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table table_hotline.
 */
public class HotLine {

    private Long id;
    /** Not-null value. */
    private String item_id;
    private Integer status;
    private String num_name;
    private String tel_description;
    private String tel;
    private String group_id;
    private String group_name;

    public HotLine() {
    }

    public HotLine(Long id) {
        this.id = id;
    }

    public HotLine(Long id, String item_id, Integer status, String num_name, String tel_description, String tel, String group_id, String group_name) {
        this.id = id;
        this.item_id = item_id;
        this.status = status;
        this.num_name = num_name;
        this.tel_description = tel_description;
        this.tel = tel;
        this.group_id = group_id;
        this.group_name = group_name;
    }
    
    public HotLine( String item_id, Integer status, String num_name, String tel_description, String tel, String group_id, String group_name) {
        this.item_id = item_id;
        this.status = status;
        this.num_name = num_name;
        this.tel_description = tel_description;
        this.tel = tel;
        this.group_id = group_id;
        this.group_name = group_name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getItem_id() {
        return item_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setItem_id(String item_id) {
        this.item_id = item_id;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getNum_name() {
        return num_name;
    }

    public void setNum_name(String num_name) {
        this.num_name = num_name;
    }

    public String getTel_description() {
        return tel_description;
    }

    public void setTel_description(String tel_description) {
        this.tel_description = tel_description;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getGroup_id() {
        return group_id;
    }

    public void setGroup_id(String group_id) {
        this.group_id = group_id;
    }

    public String getGroup_name() {
        return group_name;
    }

    public void setGroup_name(String group_name) {
        this.group_name = group_name;
    }

}
